"""Generate the documentation that ships inside the published dataset.

These files are written by the engine on every publish, from the manifest, so the numbers in
them cannot drift away from the data. Nothing here is maintained by hand.

The intended reader of ``START_HERE_AI.md`` is an AI agent with no prior context that has to
trust and correctly use this dataset within five minutes. Everything is written for that
reader: what is safe, what is not, and precisely where the line is.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any
from uuid import uuid4


# Kept out of the f-string template below, because it contains braces of its own.
VERIFY_SNIPPET = '''```python
import hashlib, json, pathlib

manifest = json.loads(pathlib.Path("MANIFEST.json").read_text())
bad = [f["path"] for f in manifest["files"]
       if hashlib.sha256(pathlib.Path(f["path"]).read_bytes()).hexdigest() != f["sha256"]]
if bad:
    print("FAIL:", bad)
else:
    print("PASS -", len(manifest["files"]), "files verified")
```'''


def _atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    encoded = text.encode("utf-8")
    if path.is_file() and path.read_bytes() == encoded:
        return
    temporary = path.with_name(f".{path.name}.{uuid4().hex}.partial")
    temporary.write_bytes(encoded)
    os.replace(temporary, path)


def _year_table(universe: dict[str, Any]) -> str:
    lines = [
        "| Year | Label | Rows | Securities | Sessions | Coverage | Membership basis |",
        "|---|---|---:|---:|---:|---|---|",
    ]
    for row in universe["years"]:
        lines.append(
            f"| {row['year']} | **{row['label']}** | {row['rows']:,} | {row['symbols']:,} | "
            f"{row['sessions']} | {row['first_date']} → {row['last_date']} | "
            f"`{row['membership_basis']}` |"
        )
    return "\n".join(lines)


def _label_summary(universe: dict[str, Any]) -> str:
    safe = universe["backtest_safe_years"]
    partial = universe["partial_years"]
    only = universe["price_data_only_years"]

    def span(years: list[int]) -> str:
        if not years:
            return "none"
        if len(years) == 1:
            return str(years[0])
        return f"{min(years)}–{max(years)}"

    return (
        f"BACKTEST_SAFE {span(safe)} · PARTIAL {span(partial)} · PRICE_DATA_ONLY {span(only)}"
    )


def _headline_table(n500: dict[str, Any], n750: dict[str, Any]) -> str:
    lines = [
        "| Universe | Rows | Securities ever present | Coverage | Year labels |",
        "|---|---:|---:|---|---|",
    ]
    for name, entry in (("nifty500", n500), ("nifty750", n750)):
        lines.append(
            f"| `{name}/` | {entry['rows']:,} | {entry['distinct_symbols']:,} "
            f"| {entry['first_date']} → {entry['last_date']} "
            f"| {_label_summary(entry)} |"
        )
    return "\n".join(lines)


def start_here(manifest: dict[str, Any], quality: dict[str, Any] | None) -> str:
    n500 = manifest["universes"]["nifty500"]
    n750 = manifest["universes"]["nifty750"]
    anchor = manifest["official_membership_anchor"]
    cal = manifest["calendar"]
    ca = manifest["corporate_actions"]
    gb = manifest["total_bytes"] / 1e9

    without_csv = manifest.get("csv_policy", {}).get("years_without_csv", {})
    missing_csv = {k: v for k, v in without_csv.items() if v}
    if missing_csv:
        parts = ", ".join(
            f"`{name}` {', '.join(str(y) for y in years)}" for name, years in missing_csv.items()
        )
        csv_status = (
            f"**In this copy of the dataset, these years have no CSV: {parts}.** Their Parquet "
            "files are complete and are the authoritative data."
        )
    else:
        csv_status = "In this copy, every year has both a Parquet file and a CSV."

    identity = manifest.get("identity", {})
    multi_isin = identity.get("symbols_with_multiple_isins", "several")
    multi_symbol = identity.get("isins_with_multiple_symbols", "several")

    quality_line = (
        "See `DATA_QUALITY_REPORT.md` for the full verification run."
        if quality
        else "`DATA_QUALITY_REPORT.md` has not been generated yet."
    )

    return f"""# START HERE — read this before using any file in this folder

*Generated by the VAJRA data engine on {manifest['generated_at_utc'][:19]}Z. Do not edit by
hand; the next publish overwrites it.*

You are looking at a point-in-time Indian equity OHLCV dataset covering
**{n500['first_date']} to {manifest['latest_session']}**, {manifest['file_count']} files,
{gb:.1f} GB. It is meant to be used for backtesting without you having to verify it first.

Read sections 1 and 2. They are the two things that will make your results wrong if you skip
them.

---

## 1. Which years you may backtest on

**This is the single most important table in the dataset.**

{_headline_table(n500, n750)}

The labels mean:

- **`BACKTEST_SAFE`** — real point-in-time membership exists for the whole year. Use freely.
- **`PARTIAL`** — membership becomes trustworthy part-way through the year. A backtest that
  starts inside the untrusted part carries survivorship bias.
- **`PRICE_DATA_ONLY`** — **the prices are real; the membership is not.** Do not present a
  backtest over these years as evidence of anything.

Every year's label is in `MANIFEST.json` under `universes.<name>.years[].label`, together with
a `membership_basis` string that says exactly what the membership is based on.

### Why the line falls where it does

For `nifty500`, official NSE constituent evidence begins on **{anchor}**. Before that, the
membership panel was built by taking the {anchor} constituent list and reversing every
official index change backwards through time. That reconstruction is careful and it is
labelled `RECONSTRUCTED_MEDIUM_CONFIDENCE` in the data itself — but it is an estimate, and a
strategy that selects on it is selecting partly on hindsight.

For `nifty750`, there is a different and more honest situation, described in section 3.

---

## 2. Point-in-time membership — the mistake that inflates every backtest

The price files contain **every security that was ever a member**, on every date it traded —
including {n500['distinct_symbols']:,} distinct securities for a 500-name index. That is
deliberate. It is what makes the dataset survivorship-safe.

It also means: **if you load the price files and ignore the membership panel, you are
backtesting on a universe that includes companies which had not yet been added and excludes
nothing that was later removed.** Your returns will be too high. This is the single most
common way to get a wrong answer from this dataset.

Always join. For `nifty500`:

```python
import duckdb

con = duckdb.connect()
rows = con.execute(\"\"\"
    SELECT p.*
    FROM read_parquet('nifty500/parquet/nifty500_*.parquet') p
    JOIN read_parquet('nifty500/membership/nifty500_daily_membership.parquet') m
      ON m.Date = p.Date AND m.ISIN = p.ISIN
    WHERE p.Date >= DATE '{anchor}'
      AND p.IsResearchEligible
\"\"\").df()
```

The membership panel is daily and already point-in-time: row `(Date, ISIN)` exists if and only
if that security was in the index on that date. There is no date arithmetic for you to get
wrong.

For `nifty750`, membership is monthly. Join on the rebalance month:

```sql
SELECT p.*
FROM read_parquet('nifty750/parquet/nifty750_*.parquet') p
JOIN read_parquet('nifty750/membership/vajra750_monthly_vajra_750_universe.parquet') u
  ON u.ISIN = p.ISIN
 AND p.Date >  CAST(u.RebalanceDate AS DATE)
 AND p.Date <= CAST(u.RebalanceDate AS DATE) + INTERVAL 1 MONTH
```

Note `p.Date > RebalanceDate`: the universe for a month is decided using data up to and
including the rebalance date, so it may only be traded from the *next* session. Joining with
`>=` leaks one day of hindsight.

---

## 3. What the two universes actually are

### `nifty500/` — a real index

{n500['definition']}

### `nifty750/` — **not an index**

{n750['definition']}

There is no such thing as a "NIFTY 750". This universe is a rule:

> Each month end, rank every eligible security by 60-day median turnover and take the top 750.
> Eligible means: at least 252 sessions of history, at least 40 turnover observations in the
> last 60 sessions, price data no more than 7 calendar days stale, and research-eligible.

Because it is a mechanical rule applied to point-in-time data, it is reproducible and
auditable — in one specific sense it is *stronger* than index membership, because you can
recompute it and check. Its weakness is the opposite one: it is not what any benchmark
tracks, so you cannot compare its returns to a published index and call that outperformance.

Its price file is a **supporting master**: it holds every security that was ever selected,
which is more securities than 750. Filter it through the membership file. Always.

---

## 4. Schema

Full column-by-column detail is in `DATA_DICTIONARY.md`. The short version:

- One row = one security on one trading session.
- `Date` is a `DATE`. `Symbol` is the NSE trading symbol **on that date**. `ISIN` is the
  identity; **join on ISIN, group on ISIN, never on Symbol.**

  This is not a stylistic preference. In this dataset **{multi_isin} symbols carry more than
  one ISIN** over time — a face-value change issues a new one — and **{multi_symbol} ISINs
  carry more than one symbol**, from renames. Computing a return with `LAG(Close)` partitioned
  by symbol rather than ISIN crosses those boundaries and invents moves: doing exactly that
  produced a fictitious +428% day for ADANIPOWER while checking this dataset. No date has the
  same `(Date, ISIN)` or `(Date, Symbol)` twice, so partitioning by ISIN is unambiguous.
- `Open`/`High`/`Low`/`Close` are in **INR**, adjusted (section 5).
- `Volume` is share count, adjusted alongside price.
- `Raw*` columns are the unadjusted exchange values, kept so you can audit any adjustment.
- Empty text fields are `NULL`, never `""`.

## 5. How prices are adjusted

Splits, bonus issues and face-value changes are applied as a **backward-cumulative multiplier**
on price, with the reciprocal applied to volume, so that the most recent close equals the
actual traded close and history is scaled to match it. `PriceAdjustmentFactor` and
`VolumeAdjustmentFactor` carry the factor used for each row, and
`AppliedOfficialCAEventIds` names the specific NSE events behind it.

**Dividends are not applied.** This is a price-return series, not total return. If you compare
a strategy's return against a Total Return Index you will understate the strategy by roughly
the dividend yield each year — historically around 1–1.5% a year for Indian large caps. Either
compare against a price index, or add an estimated dividend yield to the strategy, and say
which you did.

Where an adjustment could not be proven against observed prices, the event is **quarantined
rather than guessed**: {ca['events_quarantined']:,} of {ca['events_reconciled_against_prices']:,}
reconciled events. Rows affected by an unresolved event carry
`CorporateActionQuarantineFlag = true` and `IsResearchEligible = false`. The quarantined events
are published in full under `corporate_actions/` so you can judge them yourself.

**Filter on `IsResearchEligible` unless you have a reason not to.**

## 6. Trading calendar

`calendar/nse_trading_sessions.parquet` lists {cal['trading_sessions']:,} sessions from
{cal['first_session']} to {cal['last_session']}. A date is a session if and only if official
end-of-day data exists for it. `calendar/nse_non_trading_days.parquet` lists the rest;
weekday entries there are marked `INFERRED_NON_TRADING` — almost certainly market holidays,
but **the engine has not read an official NSE holiday circular** and does not claim to have.

## 7. Loading the data

```python
# Parquet - fast, typed, recommended
import duckdb
df = duckdb.sql("SELECT * FROM 'nifty500/parquet/nifty500_2024.parquet'").df()

# CSV - identical content, for tools without a Parquet reader
import pandas as pd
df = pd.read_csv("nifty500/csv/nifty500_2024.csv", parse_dates=["Date"])
```

The Parquet and CSV files for a given year hold **the same rows and the same values**. That is
not a claim of intent; it is checked on every publish with a full set difference in both
directions, and the publish is aborted if it fails.

### If a year has no CSV

{csv_status}

Every year always has a Parquet file. A year may legitimately have **no CSV**: the CSV is a
convenience mirror about ten times the size of the Parquet for the same rows, and deleting
CSVs to free disk space is supported and expected. The engine will not recreate a deleted CSV
for a past year — that would silently undo the space you freed — and it will not stop because
one is missing.

`MANIFEST.json` lists exactly which years have no CSV, under `csv_policy.years_without_csv`.
To get one back, delete that year's Parquet file too; the next run rebuilds both.

## 8. Verifying integrity

`MANIFEST.json` carries a SHA256 for every file. To check them all:

{VERIFY_SNIPPET}

Run it from inside this folder.

## 8b. Could you actually have traded it?

Corporate actions in this dataset are clean — every split, bonus and face-value change in the
official NSE archive has been checked against the price series and applied. So the remaining
way to get a wrong backtest is subtler: **the price is correct and nobody could have traded at
it.**

Two columns are provided so you can filter for your own position size:

- **`IsFrozenBar`** — `true` when open = high = low = close. The session had no intraday range
  at all: a circuit limit, or a single trade. If your backtest fills anywhere other than that
  one price on such a bar, it is inventing a fill.
- **`TurnoverINR`** — the session's traded value in rupees. A stock turning over a lakh a day
  cannot absorb a real position, and your own order would have moved the price.

`DATA_QUALITY_REPORT.md` carries the measured shares for both universes. As a rough guide:
roughly 0.2% of research-eligible rows are frozen bars, and single-digit percentages fall
below Rs 10 lakh of daily turnover — higher in `nifty750`, which reaches further down the
size curve.

**These rows are reported, never removed.** They are real liquidity characteristics of Indian
mid and small caps, not data errors, and deleting them would quietly narrow the universe and
flatter your results. Filtering is your decision, and it should match the capital you intend
to deploy.

## 8c. What `Close` actually is, and which series you are holding

**`Close` is NSE's official closing price** — a volume-weighted average of the final half
hour of trading — **not the last traded price.** Every raw price in this dataset has been
compared against NSE's own published bhavcopy and matches to within half a paisa.

This matters when you compare against another data provider. Most free sources carry the
*last traded* price, so on a volatile day they will differ from this dataset by tenths of a
percent. That is a difference of definition, not an error on either side. If your backtest
assumes it fills at the last trade, model that yourself; `Close` here is the settlement-style
figure.

**The `Series` column is not decoration.** Rows marked `EQ` are the ordinary rolling segment.
Rows marked **`BE` are the trade-to-trade segment** and `BZ` the non-compliant segment, where
intraday trading is prohibited and every trade must be settled by delivery. A backtest that buys
and sells such a security within the same session is modelling something the exchange does not
permit.

These rows are here on purpose, and the reason is worth stating plainly. An earlier version of
this dataset kept only `EQ`. A security placed under surveillance therefore disappeared from its
own price history for the whole period — no error, no warning, simply absent rows. On the session
it returned to `EQ`, the computed one-day return spanned the entire gap: one name showed +58.6%
for what was really a 98-day move. Across seventeen years that produced 306 such breaks in 206
liquid names.

**Filter on `Series = 'EQ'` before selecting positions, but keep every row when computing
returns.** Those are two different questions and they need two different filters.

## 9. What NOT to assume

1. **Do not assume the price files are the universe.** They are the superset. See section 2.
2. **Do not join or group on `Symbol` across time.** {multi_isin} symbols in this dataset
   carry more than one ISIN. Use `ISIN`. See section 4.
3. **Do not compare returns to a Total Return Index.** No dividends. See section 5.
4. **Do not treat `PRICE_DATA_ONLY` years as backtestable.** See section 1.
5. **Do not assume every session has every member.** A member with no trade that day has no
   row. Reindex explicitly if your code needs a rectangular panel.
6. **Do not drop quarantined rows silently and report the result as clean.** Say how many you
   dropped.
7. **Do not assume `nifty750` is an index.** It is not. See section 3.
8. **Do not assume a stale-looking last date means the data is broken.** See section 10.
9. **Do not assume a missing CSV means missing data.** The Parquet is the dataset. See
   section 7.
10. **Do not assume every eligible row was tradeable at your size.** See section 8b.
11. **Do not assume `Close` is the last traded price, or that every row is intraday-tradeable.**
    See section 8c.

## 10. How this stays current, and what it survives

An engine on the owner's laptop updates this folder automatically. It fetches every trading
session it has not yet certified — if the laptop was off for a month, the next run catches up
all of it unattended, then republishes and updates `MANIFEST.json` and `CHANGELOG.md`.

So a last date a few days behind today is normal and self-correcting. `CHANGELOG.md` shows
when each publish happened.

It also repairs this folder. On every run:

| What is wrong | What happens |
|---|---|
| A Parquet file is missing or corrupt | Rebuilt from the engine's working store |
| A CSV for a past year is missing | **Left missing on purpose.** See section 7 |
| A CSV for the current year is missing | Rewritten, so new data always has one |
| Both files for a year are missing | Both rebuilt — this is a real gap, not a disk decision |
| `MANIFEST.json` is missing or unreadable | Rebuilt from what is on disk |
| The documentation files are missing | Regenerated |
| This whole folder is deleted | Entirely rebuilt on the next run |
| The engine cannot reach NSE | The run stops and **this folder is left untouched** |

The last row is the important one. A failed run never leaves a half-written dataset behind:
what you are reading is always the last version that passed every check.

## 11. Honest limitations

- Price return only; no dividends ({ca['events_reconciled_against_prices']:,} corporate
  actions reconciled, dividends recorded but deliberately not applied).
- `nifty500` membership before {anchor} is reconstructed, not official.
- `nifty750` is a self-defined universe, not a benchmark.
- {ca['events_quarantined']:,} corporate actions could not be proven and were quarantined
  rather than applied.
- Non-trading weekdays in the calendar are inferred from data presence, not from an official
  holiday list.
- Coverage starts {n500['first_date']}. Nothing before that exists in this folder.
- {quality_line}

---

*If any statement in this file disagrees with `MANIFEST.json`, trust `MANIFEST.json` — it is
generated directly from the files.*
"""


def data_dictionary(manifest: dict[str, Any], schemas: dict[str, list[dict[str, str]]]) -> str:
    sections = []
    for name, columns in schemas.items():
        rows = [
            "| Column | Type | Units | Meaning |",
            "|---|---|---|---|",
        ]
        for column in columns:
            rows.append(
                f"| `{column['name']}` | {column['type']} | {column.get('units', '—')} | "
                f"{column.get('meaning', '')} |"
            )
        sections.append(f"## {name}\n\n" + "\n".join(rows))
    body = "\n\n".join(sections)
    return f"""# DATA DICTIONARY

*Generated on {manifest['generated_at_utc'][:19]}Z. Companion to `START_HERE_AI.md`, which
explains how to use the data; this file explains what each column is.*

Conventions that apply everywhere:

- Currency is **INR**. Prices are per share.
- `Date` is a calendar date with no time component and no timezone. All sessions are NSE
  trading days in IST.
- Missing text is `NULL`, never the empty string.
- A missing `(Date, ISIN)` row means the security did not trade that session. It does not mean
  zero volume.
- `ISIN` is the stable identity across renames. `Symbol` is the ticker on that date only.

{body}
"""


def write_all(
    root: Path,
    manifest: dict[str, Any],
    *,
    quality: dict[str, Any] | None = None,
    schemas: dict[str, list[dict[str, str]]] | None = None,
) -> list[str]:
    written: list[str] = []
    _atomic_text(root / "START_HERE_AI.md", start_here(manifest, quality))
    written.append("START_HERE_AI.md")
    if schemas is None:
        schemas = describe_schemas(root)
    _atomic_text(root / "DATA_DICTIONARY.md", data_dictionary(manifest, schemas))
    written.append("DATA_DICTIONARY.md")
    return written


COLUMN_NOTES: dict[str, tuple[str, str]] = {
    "Date": ("date", "Trading session. NSE calendar, IST, no time component."),
    "Symbol": ("—", "NSE trading symbol on that date. Changes on rename; do not join on it."),
    "MembershipSymbol": ("—", "Symbol as it appeared in the index constituent file that day."),
    "ISIN": ("—", "Stable security identity. Join and group on this."),
    "ExchangeISIN": ("—", "ISIN as printed in the exchange bhavcopy, kept for cross-checking."),
    "Series": (
        "—",
        "NSE series code. `EQ` is the ordinary rolling segment. **`BE` is trade-to-trade** and "
        "`BZ` is the non-compliant segment: intraday trading is prohibited there and every trade "
        "settles by delivery. These rows are included so that a security which moves into "
        "surveillance does not vanish from its own price history — without them the session it "
        "returns on shows a multi-month move as a one-day return. They are excluded from the "
        "tradeable universe on the days they carry a non-`EQ` code. Filter on `Series = 'EQ'` "
        "before selecting positions.",
    ),
    "Open": ("INR", "Adjusted opening price."),
    "High": ("INR", "Adjusted session high."),
    "Low": ("INR", "Adjusted session low."),
    "Close": ("INR", "Adjusted closing price. The most recent close is unadjusted by construction."),
    "Volume": ("shares", "Adjusted traded quantity."),
    "RawOpen": ("INR", "Unadjusted exchange open."),
    "RawHigh": ("INR", "Unadjusted exchange high."),
    "RawLow": ("INR", "Unadjusted exchange low."),
    "RawClose": ("INR", "Unadjusted exchange close."),
    "RawVolume": ("shares", "Unadjusted exchange traded quantity."),
    "RawPrevClose": ("INR", "Previous close as printed by the exchange."),
    "RawTurnover": ("INR", "Traded value for the session."),
    "RawTotalTrades": ("count", "Number of trades executed."),
    "PriceAdjustmentFactor": (
        "ratio",
        "Backward-cumulative multiplier applied to raw price to get the adjusted price.",
    ),
    "VolumeAdjustmentFactor": ("ratio", "Reciprocal factor applied to raw volume."),
    "AdjustmentSource": ("—", "Which source produced the factor."),
    "AdjustmentConfidence": ("—", "How strongly the factor is evidenced."),
    "AdjustmentSourceFile": ("—", "File the factor was derived from."),
    "AdjustmentSourceSha256": ("—", "SHA256 of that file, for provenance."),
    "AdjustmentIdentityMapSha256": ("—", "SHA256 of the symbol-identity map used."),
    "AppliedOfficialCAEventIds": ("—", "Comma-separated NSE corporate-action event ids applied."),
    "RawSourceArchive": ("—", "Bhavcopy archive this row came from."),
    "RawSourceSha256": ("—", "SHA256 of that archive."),
    "MembershipConfidence": (
        "—",
        "OFFICIAL... for dates with real constituent evidence; RECONSTRUCTED_MEDIUM_CONFIDENCE "
        "before the official anchor.",
    ),
    "MembershipEvidence": ("—", "What the membership claim rests on."),
    "FoundationVersion": ("—", "Version of the build that produced the row."),
    "IdentityStatus": ("—", "How the security identity was resolved."),
    "OfficialCAQuarantine": ("bool", "An official corporate action could not be applied."),
    "OfficialCAQuarantineReason": ("—", "Why. NULL when not quarantined."),
    "RelistingQuarantine": ("bool", "Suspended/relisted with a long price gap."),
    "RelistingQuarantineReason": ("—", "Why. NULL when not quarantined."),
    "CorporateActionQuarantineFlag": ("bool", "Any quarantine applies to this row."),
    "CorporateActionQuarantineReason": ("—", "Combined reason. NULL when not quarantined."),
    "AdjustedReturn1D": ("fraction", "One-session return on adjusted close. 0.01 = +1%."),
    "RawReturn1D": ("fraction", "One-session return on raw close, before adjustment."),
    "GapDays": ("calendar days", "Days since this security's previous observed session."),
    "DiscontinuityClassification": ("—", "How a price jump at this row was classified."),
    "UnresolvedAdjustmentDiscontinuityFlag": (
        "bool",
        "A jump remains that no known corporate action explains.",
    ),
    "ExtremeOfficialMarketMoveFlag": ("bool", "Move is extreme but matches the official record."),
    "IsResearchEligible": (
        "bool",
        "**Filter on this.** False where a quarantine or unresolved discontinuity applies.",
    ),
    "PointInTimePriceEligibilityClose": ("INR", "Close usable for point-in-time screening."),
    "Turnover": ("INR", "Traded value for the session."),
    "TotalTrades": ("count", "Number of trades executed."),
    "QuantityPerTrade": ("shares", "Average shares per trade."),
    "DeliveryQuantity": ("shares", "Shares taken to delivery rather than squared off intraday."),
    "PrevClose": ("INR", "Previous session close."),
    "Return1D": ("fraction", "One-session return."),
    "HistoryCount": ("sessions", "Sessions observed for this security up to and including today."),
    "MedianTurnover60": ("INR", "60-session median turnover. The VAJRA 750 ranking key."),
    "TurnoverObservations60": ("count", "Turnover observations in the last 60 sessions."),
    "LargeReturnAnomalyFlag": ("bool", "Return large enough to warrant inspection."),
    "LongGapOver30DaysFlag": ("bool", "More than 30 calendar days since the previous session."),
    "IsWarmupPeriod": ("bool", "Inside the warm-up window; not usable for selection."),
    "IsBacktestPeriod": ("bool", "Inside the intended backtest window."),
    "IsLiveOutOfSample": ("bool", "After the backtest window; genuine out-of-sample."),
    "CorporateActionPriceFactor": ("ratio", "Cumulative price adjustment factor."),
    "CorporateActionVolumeFactor": ("ratio", "Cumulative volume adjustment factor."),
    "Year": ("—", "Calendar year. Redundant with Date; kept for convenience."),
    "IsFrozenBar": (
        "bool",
        "**Tradability.** True when open = high = low = close: the session had no intraday "
        "range at all, meaning a circuit limit or a single trade. A fill at any other price "
        "on such a bar is invented.",
    ),
    "TurnoverINR": (
        "INR",
        "**Tradability.** Traded value for the session. Filter on this to match your own "
        "position size; a stock turning over a lakh a day cannot absorb a real order.",
    ),
}


def describe_schemas(root: Path) -> dict[str, list[dict[str, str]]]:
    import duckdb

    connection = duckdb.connect()
    connection.execute("SET enable_progress_bar=false")
    out: dict[str, list[dict[str, str]]] = {}
    targets = {
        "`nifty500/parquet/nifty500_YYYY.parquet` — NIFTY 500 adjusted OHLCV": sorted(
            (root / "nifty500" / "parquet").glob("*.parquet")
        )[-1:],
        "`nifty750/parquet/nifty750_YYYY.parquet` — VAJRA 750 supporting adjusted master": sorted(
            (root / "nifty750" / "parquet").glob("*.parquet")
        )[-1:],
        "`nifty500/membership/nifty500_daily_membership.parquet` — daily point-in-time membership": [
            root / "nifty500" / "membership" / "nifty500_daily_membership.parquet"
        ],
        "`nifty750/membership/vajra750_monthly_vajra_750_universe.parquet` — monthly universe": [
            root / "nifty750" / "membership" / "vajra750_monthly_vajra_750_universe.parquet"
        ],
        "`corporate_actions/corporate_actions_applied.parquet` — events applied to prices": [
            root / "corporate_actions" / "corporate_actions_applied.parquet"
        ],
        "`calendar/nse_trading_sessions.parquet` — trading calendar": [
            root / "calendar" / "nse_trading_sessions.parquet"
        ],
    }
    for label, files in targets.items():
        files = [f for f in files if f.is_file()]
        if not files:
            continue
        schema = connection.execute(
            f"DESCRIBE SELECT * FROM read_parquet('{str(files[0]).replace(chr(92), '/')}')"
        ).fetchall()
        columns = []
        for name, dtype, *_ in schema:
            units, meaning = COLUMN_NOTES.get(name, ("—", ""))
            columns.append({"name": name, "type": dtype, "units": units, "meaning": meaning})
        out[label] = columns
    return out


__all__ = ["data_dictionary", "describe_schemas", "start_here", "write_all"]
